author:
  name: Tom Weglarz
  role: Christ First
  bio:  Searching for my first business acquisition with Acquisiion Ace.
  location: Dallas-Fort Worth, Texas

social:
  - id: "x"
    label: "X"
    href: "#_"
  - id: "github"
    label: "GitHub"
    href: "https://github.com/roicort"
  - id: "linkedin"
    label: "Linkedin"
    href: "#_"
  - id: "email"
    label: "Email"
    href: "mailto:"
